#main configuration
title: DynamicBytes
description: Practical programming and cybersecurity content for beginners.
baseurl: ""
url: "https://dynamicbytes.blog"
theme: minima
lang: en
timezone: Africa/Lagos


#navigation menu
header_pages:
  - about.md

#layout for posts
markdown: kramdown
permalink: /:title/

#plugins lists
plugins:
  - jekyll-feed #used for feed updates
  - jekyll-seo-tag #used for tags for Search Engine Optimization
  - jekyll-sitemap #used for sitemal XMLs

# SEO metadata
author: small-python
logo: /assets/images/terminal-icon1.png

# Social usernames (used by Minima)
github_username: small-python
twitter_username: laaanreewaju

# Custom footer links (for Telegram & Discord)
footer_links:
  - name: Telegram
    url: https://t.me/Lanree001 
  - name: Discord
    url: https://discord.com/users/1149862172260847627
